#!/bin/sh
set -e
# Automatically added by cargo-deb
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop peach-go-sbot.service >/dev/null || true
fi
# End automatically added section