- hosts: vps
  user: root
  tasks:
    - include_vars: vars.yaml

    - name: Setup users and groups
      block:
      - name: Ensure groups exist
        group:
          name: peach
          state: present

      - name: Ensure users exist
        ansible.builtin.user:
          name: "{{ item }}"
          state: present
          groups: "peach"
        loop:
          - notplants
          - glyph

    - name: ensure log directory
      action: file dest={{log_dir}} state=directory

    - name: ensure src directory
      action: file dest={{src_dir}} state=directory

    - name: ensure www directory
      action: file dest=/srv/www state=directory

    - name: install packages
      apt:
        pkg:
          - git
          - nginx
          - curl
          - build-essential

    - name: install rust by rustup
      shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
      args:
        creates: /root/.cargo/bin/rustc

    - name: install cargo deb
      shell: /root/.cargo/bin/cargo install cargo-deb
      args:
        creates: /root/.cargo/bin/cargo-deb

    - name: copy main nginx config
      action: template src=nginx/nginx.conf dest=/etc/nginx/nginx.conf


