app_name: peach-vps
log_dir: /srv/log
src_dir: /srv/src
web_dir: /srv/www
debian_rep_dir: /srv/www/repos/apt/debian
gpg_key_id: E62CD13A85763FCEC3EDBA8EA98440817F1A3CE5
services:
  - peach-oled
  - peach-stats
  - peach-web